# Generated by Django 4.2.7 on 2023-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLoom_app_1', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.CharField(default='Not set', max_length=110),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default='Not set', max_length=30),
        ),
    ]
